# -*- coding: utf-8 -*-
import os

from output_key import output_key
from Generetion_Simple_Number import Prime_Number
from  input_txt import input_txt
from input_key import input_key
from signature import signature
from check_signature import check_signature
from  input_signature import input_signature

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QPalette, QBrush


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 734)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 734))
        MainWindow.setMaximumSize(QtCore.QSize(1400, 734))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 0));")
        self.toolBox.setObjectName("toolBox")
        self.generetion_key_page = QtWidgets.QWidget()
        self.generetion_key_page.setGeometry(QtCore.QRect(0, 0, 1388, 620))
        self.generetion_key_page.setObjectName("generetion_key_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.generetion_key_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_radio = QtWidgets.QFrame(self.generetion_key_page)
        self.frame_radio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_radio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_radio.setObjectName("frame_radio")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_radio)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_radio)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_radio_1 = QtWidgets.QLabel(self.frame_4)
        self.label_radio_1.setObjectName("label_radio_1")
        self.verticalLayout_4.addWidget(self.label_radio_1)
        self.label_radio_2 = QtWidgets.QLabel(self.frame_4)
        self.label_radio_2.setObjectName("label_radio_2")
        self.verticalLayout_4.addWidget(self.label_radio_2)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_radio)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.my_prime = QtWidgets.QRadioButton(self.frame_5)
        self.my_prime.setText("")
        self.my_prime.setObjectName("my_prime")
        self.verticalLayout_5.addWidget(self.my_prime)
        self.user_prime = QtWidgets.QRadioButton(self.frame_5)
        self.user_prime.setText("")
        self.user_prime.setObjectName("user_prime")
        self.verticalLayout_5.addWidget(self.user_prime)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.frame_radio)
        self.frame_2 = QtWidgets.QFrame(self.generetion_key_page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_label_your_primes = QtWidgets.QFrame(self.frame_2)
        self.frame_label_your_primes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_your_primes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_your_primes.setObjectName("frame_label_your_primes")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_label_your_primes)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_window_your_primes = QtWidgets.QLabel(self.frame_label_your_primes)
        self.label_window_your_primes.setObjectName("label_window_your_primes")
        self.verticalLayout_11.addWidget(self.label_window_your_primes)
        self.frame_input_primes = QtWidgets.QFrame(self.frame_label_your_primes)
        self.frame_input_primes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_primes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_primes.setObjectName("frame_input_primes")
        self.formLayout = QtWidgets.QFormLayout(self.frame_input_primes)
        self.formLayout.setObjectName("formLayout")
        self.label_first_number = QtWidgets.QLabel(self.frame_input_primes)
        self.label_first_number.setObjectName("label_first_number")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_first_number)
        self.line_input_first_prime = QtWidgets.QLineEdit(self.frame_input_primes)
        self.line_input_first_prime.setObjectName("line_input_first_prime")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_input_first_prime)
        self.label_second_number = QtWidgets.QLabel(self.frame_input_primes)
        self.label_second_number.setObjectName("label_second_number")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_second_number)
        self.line_input_second_prime = QtWidgets.QLineEdit(self.frame_input_primes)
        self.line_input_second_prime.setObjectName("line_input_second_prime")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_input_second_prime)
        self.verticalLayout_11.addWidget(self.frame_input_primes)
        self.verticalLayout_6.addWidget(self.frame_label_your_primes)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_button_input_primes = QtWidgets.QFrame(self.generetion_key_page)
        self.frame_button_input_primes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button_input_primes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_input_primes.setObjectName("frame_button_input_primes")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_button_input_primes)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Button_key_generation = QtWidgets.QPushButton(self.frame_button_input_primes)
        self.Button_key_generation.setObjectName("Button_key_generation")
        self.verticalLayout_3.addWidget(self.Button_key_generation)
        self.Button_key_generation.clicked.connect(lambda: self.fun_key_generation(self.my_prime.isChecked()))
        self.verticalLayout_2.addWidget(self.frame_button_input_primes)
        self.toolBox.addItem(self.generetion_key_page, "")
        self.signarute_frame = QtWidgets.QWidget()
        self.signarute_frame.setGeometry(QtCore.QRect(0, 0, 1388, 620))
        self.signarute_frame.setObjectName("signarute_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.signarute_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_input_patch_file = QtWidgets.QFrame(self.signarute_frame)
        self.frame_input_patch_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_patch_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_patch_file.setObjectName("frame_input_patch_file")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_input_patch_file)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_input_open_file = QtWidgets.QFrame(self.frame_input_patch_file)
        self.frame_input_open_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_open_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_open_file.setObjectName("frame_input_open_file")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_input_open_file)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_path_open_key = QtWidgets.QLabel(self.frame_input_open_file)
        self.label_path_open_key.setObjectName("label_path_open_key")
        self.horizontalLayout_5.addWidget(self.label_path_open_key)
        self.line_path_open_key = QtWidgets.QLineEdit(self.frame_input_open_file)
        self.line_path_open_key.setObjectName("line_path_open_key")
        self.horizontalLayout_5.addWidget(self.line_path_open_key)
        self.verticalLayout_8.addWidget(self.frame_input_open_file)
        self.frame_input_text_file = QtWidgets.QFrame(self.frame_input_patch_file)
        self.frame_input_text_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_text_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_text_file.setObjectName("frame_input_text_file")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_input_text_file)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_path_text = QtWidgets.QLabel(self.frame_input_text_file)
        self.label_path_text.setObjectName("label_path_text")
        self.horizontalLayout_4.addWidget(self.label_path_text)
        self.line_path_text_key = QtWidgets.QLineEdit(self.frame_input_text_file)
        self.line_path_text_key.setObjectName("line_path_text_key")
        self.horizontalLayout_4.addWidget(self.line_path_text_key)
        self.verticalLayout_8.addWidget(self.frame_input_text_file)
        self.verticalLayout_7.addWidget(self.frame_input_patch_file)
        self.frame_button_signature = QtWidgets.QFrame(self.signarute_frame)
        self.frame_button_signature.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button_signature.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_signature.setObjectName("frame_button_signature")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_button_signature)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_signature = QtWidgets.QPushButton(self.frame_button_signature)
        self.button_signature.setObjectName("button_signature")
        self.button_signature.clicked.connect(lambda: self.fun_signature())
        self.horizontalLayout_6.addWidget(self.button_signature)
        self.verticalLayout_7.addWidget(self.frame_button_signature)
        self.toolBox.addItem(self.signarute_frame, "")
        self.signature_check_page = QtWidgets.QWidget()
        self.signature_check_page.setObjectName("signature_check_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.signature_check_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_input_check_file = QtWidgets.QFrame(self.signature_check_page)
        self.frame_input_check_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_check_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_check_file.setObjectName("frame_input_check_file")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_input_check_file)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_input_close_key_file = QtWidgets.QFrame(self.frame_input_check_file)
        self.frame_input_close_key_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_close_key_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_close_key_file.setObjectName("frame_input_close_key_file")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_input_close_key_file)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_path_close_key = QtWidgets.QLabel(self.frame_input_close_key_file)
        self.label_path_close_key.setObjectName("label_path_close_key")
        self.horizontalLayout_7.addWidget(self.label_path_close_key)
        self.line_path_close_key = QtWidgets.QLineEdit(self.frame_input_close_key_file)
        self.line_path_close_key.setObjectName("line_path_close_key")
        self.horizontalLayout_7.addWidget(self.line_path_close_key)
        self.verticalLayout_10.addWidget(self.frame_input_close_key_file)
        self.frame_input_signature_check_file = QtWidgets.QFrame(self.frame_input_check_file)
        self.frame_input_signature_check_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_signature_check_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_signature_check_file.setObjectName("frame_input_signature_check_file")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_input_signature_check_file)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.path_labe_signature_check = QtWidgets.QLabel(self.frame_input_signature_check_file)
        self.path_labe_signature_check.setObjectName("path_labe_signature_check")
        self.horizontalLayout_8.addWidget(self.path_labe_signature_check)
        self.line_path_signature_check = QtWidgets.QLineEdit(self.frame_input_signature_check_file)
        self.line_path_signature_check.setObjectName("line_path_signature_check")
        self.horizontalLayout_8.addWidget(self.line_path_signature_check)
        self.verticalLayout_10.addWidget(self.frame_input_signature_check_file)
        self.verticalLayout_9.addWidget(self.frame_input_check_file)
        self.frame_button_signature_check = QtWidgets.QFrame(self.signature_check_page)
        self.frame_button_signature_check.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button_signature_check.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_signature_check.setObjectName("frame_button_signature_check")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_button_signature_check)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.button_check_signature = QtWidgets.QPushButton(self.frame_button_signature_check)
        self.button_check_signature.setObjectName("button_check_signature")
        self.horizontalLayout_9.addWidget(self.button_check_signature)
        self.button_check_signature.clicked.connect(lambda: self.func_check_signature())
        self.verticalLayout_9.addWidget(self.frame_button_signature_check)
        self.toolBox.addItem(self.signature_check_page, "")
        self.verticalLayout.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_radio_1.setText(_translate("MainWindow", "генерировать простые числа"))
        self.label_radio_2.setText(_translate("MainWindow", "свои числа"))
        self.label_window_your_primes.setText(_translate("MainWindow", "Свои простые числа"))
        self.label_first_number.setText(_translate("MainWindow", "первое число"))
        self.label_second_number.setText(_translate("MainWindow", "второе число"))
        self.Button_key_generation.setText(_translate("MainWindow", "Генерировать"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.generetion_key_page), _translate("MainWindow", "Генерация ключей"))
        self.label_path_open_key.setText(_translate("MainWindow", "Файл с открытым ключём"))
        self.label_path_text.setText(_translate("MainWindow", "Файл с текстом               "))
        self.button_signature.setText(_translate("MainWindow", "Подписать"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.signarute_frame), _translate("MainWindow", "Подпись файла"))
        self.label_path_close_key.setText(_translate("MainWindow", "Файл с закрытым ключом      "))
        self.path_labe_signature_check.setText(_translate("MainWindow", "Файл с подписанным текстом"))
        self.button_check_signature.setText(_translate("MainWindow", "проверка"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.signature_check_page), _translate("MainWindow", "Проверка подписи"))


    def func_check_signature(self):
        path_open_key = self.line_path_close_key.text()
        path_signature = self.line_path_signature_check.text()
        print(1)
        key = input_key()
        print(2)
        key.input_open_key(path_open_key)
        print(3)
        open_exhibitor, multiplication = key.open_key()
        print(4)
        sig = input_signature()
        print(5)
        sig.input(path_signature)
        print(6)
        signature_text = sig.getText()
        print(7)

        signature = sig.getSignaturee()
        print(8)

        check_signature(open_exhibitor, multiplication, signature_text, signature, path_signature)
        print(9)


    def fun_signature(self):
        path_close_key = self.line_path_open_key.text()
        path_signature = self.line_path_text_key.text()
        text = input_txt(path_signature).input_txt()
        key = input_key()
        key.input_close_key(path_close_key)
        close_exhibitor, multiplication = key.close_key()
        signature(text, close_exhibitor, multiplication)



    def fun_key_generation(self, my_prime):
        if(my_prime):
            number_pryme = Prime_Number(1024)
            first, second = number_pryme.number()
            key = output_key(first, second)
        else:
            try:
                print(self.line_input_second_prime.text())
                first = int(self.line_input_first_prime.text())
                second = int(self.line_input_second_prime.text())
                key = output_key(first, second)
            except ValueError:
                print("Ошибка с веденными числами")




def resource_path0(relative_path):
    base_path = getattr(
        sys,
        '_MEIPASS',
        os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    palette = QPalette()
    path = resource_path0("RSA_logo_Logo.jpg");
    palette.setBrush(QPalette.Background, QBrush(QPixmap(path)))
    MainWindow.setPalette(palette)
    MainWindow.show()
    sys.exit(app.exec_())